[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/tjquillan"

[social.params]
icon = "brand-github"

[[social]]
identifier = "gitlab"
name = "GitLab"
url = "https://gitlab.com/tjquillan"

[social.params]
icon = "brand-gitlab"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/thomas-quillan/"

[social.params]
icon = "brand-linkedin"
